### ISSUE TITLE
Countdown 

### ISSUE THREAD

**Issue by FranticDav** [fmbot-discord/fmbot#112]
In a server we're in, we love to have listening parties and we usually count down ourselves so we start the album at the same time.

Is there a possibility to add a countdown feature to the bot? It would work as follows

`.fmcountdown`

and the bot would post this (one message per second):

`COUNTDOWN!`
`10`
`9`
`8`
`7`
`6`
`5`
`4`
`3`
`2`
`1`
`GO!`

**Comment by th0mk** [comment]
@FranticDav I've added `.fmcountdown`. It counts down from 3 because Discord seems to ratelimit for some reason.
You can also try `.fmcountdown 5` but it has the ratelimiting.
