### ISSUE TITLE
Man On The Moon: The Legend of Mr. Rager

### ISSUE THREAD

**Issue by spukknik1** [fmbot-discord/fmbot#113]
![81OPlzQ2cwL _SL1400_](https://user-images.githubusercontent.com/73042308/96354523-53d32f80-10e0-11eb-9464-bc54aa6c9aba.jpg)
**What command would you like to see improved or added?**

**What exactly should it do?**

**Additional context**

**Comment by th0mk** [comment]
Hi, I think you meant to add this image to last.fm? We use last.fm as our source for music tracking and album covers. 
The cover you sent is already available here: https://www.last.fm/music/Kid+Cudi/Man+on+the+Moon+II:+The+Legend+of+Mr.+Rager/+images/686cff186b134340827fa08930c04ff1

If you meant to do something else please let me know, but these issues are meant for feature requests and bug reports so I'll close this for now.
