### ISSUE TITLE
Limiting .fmbot responses to chosen channels.

### ISSUE THREAD

**Issue by AymenSama** [fmbot-discord/fmbot#115]
**Description**
It would be useful if there was a command that would allow for limiting all bot responses to one or more channels.

**Expected Behavior**
Basically using commands anywhere else but in the chosen channels won't trigger bot responses.

**Why Is This Needed**
In big servers commands and bot responses could be abused and spammed, one way around that is to add/update permission overrides for the bot in channels and/or categories, only that it's not completely clean and in a server with tens of channels it can be a lot of work and time consuming.

**Comment by th0mk** [comment]
@AymenSama Just updated the bot, it's now possible to enable/disable commands in specific channels using `.fmtogglecommand`. 

More info here: https://fmbot.xyz/guildsettings/#fmtogglecommand
