### ISSUE TITLE
Follow Someone on Last.fm Using Bot

### ISSUE THREAD

**Issue by Vanmax22** [fmbot-discord/fmbot#116]
Since the bot now has access to our last.fm accounts and now can love tracks, it would be useful to be able to friend someone using the bot.

For example using ```.fmfollow lastfm``` would follow last.fm on last.fm

**Comment by th0mk** [comment]
Hey, this would be cool but the last.fm API doesn't allow this. Maybe in a future new API but for now its not possible :(
