### ISSUE TITLE
Improve .fms compatibility with Apple Music scrobbling

### ISSUE THREAD

**Issue by Hum4n01d** [fmbot-discord/fmbot#121]
**What command would you like to see improved or added?**
Spotify searches often fail with Apple Music tracks since the album titles have extra keywords in them

**What exactly should it do?**
- Remove ` - Single` and ` - EP` from Spotify queries
- Retry queries with the album removed entirely as a fallback

**Comment by th0mk** [comment]
The two keywords you mentioned are now stripped from searches (released to all bots). 

I have no idea how close we are to the Spotify ratelimit, so I will not be implementing the fallback with extra search for now. If you have additional keywords you think I should strip please let me know.
