### ISSUE TITLE
Ability to Delete .fmbot's response for users who cannot delete messages

### ISSUE THREAD

**Issue by Vanmax22** [fmbot-discord/fmbot#125]
**What command would you like to see improved or added?**
A lot of times people enter the wrong command or the wrong artist, or Last.fm just returns an error. It would be nice if there was a way, such as an X reaction, for users to delete their response from .fmbot so users without the "manage message" permissions can delete the .fmbot message.

**Comment by th0mk** [comment]
This has been added. 

Right-click (or long-press on mobile) on a message > Apps > Delete response
