### ISSUE TITLE
Fmbot won’t change songs 

### ISSUE THREAD

**Issue by Decipher828** [fmbot-discord/fmbot#127]
I listened to one song yesterday on Spotify and now whenever I try to do .fm the bot shows that same song even when I’m listening to a different one. I don’t know why it won’t change.

**Comment by th0mk** [comment]
Is it not showing what's on your Last.fm profile?

Because this doesn't sound like an .fmbot issue, but like a Last.fm issue.

See also: https://fmbot.xyz/faq/#commands-are-showing-the-wrong-songs-its-not-showing-what-i-listen-to-on-spotify
