### ISSUE TITLE
The Ability to Set A Start Date for a Server

### ISSUE THREAD

**Issue by Logey** [fmbot-discord/fmbot#129]
**What command would you like to see improved or added?**
I think it would be cool for server admins to be able to set a date that scrobbles should be tracked from (for example, the date that .fmbot was added to the server). Any scrobbles from the user before that date should be ignored.

**What exactly should it do?**
Allow server admins to set a minimum date for scrobbles. Any scrobbles before the date set should be ignored in that server.

**Additional context**
This would help incentivise newer users to sign up to last.fm and use .fmbot - as currently newer users of last.fm do not stand a chance to get most plays compared to people who have used last.fm for years.

**Comment by th0mk** [comment]
Hey, this is a cool idea but technically very difficult to achieve. We rely on Last.fm to get users their top artist/albums/tracks and those endpoints only support specific time periods like year/quarter/month etc.

If we would only count scrobbles after a specific date that would mean we would have to fetch all scrobbles for every user, then calculate their playcounts based on scrobbles for a specific time period. This being a per-server setting means we would have to calculate this independently for every server. While it would technically be possible to write a query that does it, it would mean that every time someone runs whoknows we'd have to recalculate playcounts for every user in that server based on specific scrobbles.

Maybe the explanation is a bit too technical, but the TL;DR is that it's technically not possible at our scale. Closing for now.
