### ISSUE TITLE
Link Last.fm Albums on Failed Chart Image Fetch

### ISSUE THREAD

**Issue by djanatyn** [fmbot-discord/fmbot#130]
**What command would you like to see improved or added?**
The `.fmc` command [sends a default grey image when it's unable to pull down album art](https://github.com/fmbot-discord/fmbot/blob/0a2c93d8d859bcd5aab65c92155682d1d7017d9e/src/FMBot.Bot/Services/ChartService.cs#L88):
```csharp
else
{
    chartImage = SKBitmap.Decode(FMBotUtil.GlobalVars.ImageFolder + "unknown.png");
    validImage = false;
}
```
![chart](https://user-images.githubusercontent.com/523628/116086420-cd3e7280-a66d-11eb-8a29-7e66156908a9.png)

Example:
* https://cdn.discordapp.com/attachments/783750543180693534/835199017779986482/chart-3w-3h-Week-djanatyn.png

If users update the album art on Last.fm, the chart will start returning images:
![good](https://user-images.githubusercontent.com/523628/116086658-070f7900-a66e-11eb-9155-c83f96931df2.png)

Example:
* https://cdn.discordapp.com/attachments/783750543180693534/836223666982223882/chart-3w-3h-Week-djanatyn.png

**What exactly should it do?**
The `.fmc` command should provide the user with a link to any albums that failed to retrieve, with a quick explanation on how to contribute album art. Maybe something like:
```markdown
Failed to find album art for the following albums! Can you upload them?
* https://www.last.fm/music/Puar/PUAR+BEATS+VOL3
* https://www.last.fm/music/Clyde+automaton/My+Brain+&+Other+Animals
```
If the link is unable to be fetched, then no feedback needs to be provided for that link (as there's no way to fix).

**Additional context**
I don't think most users are aware of how to fix missing images (I had to read through the code to find out).
If every user with a missing album art is informed of a potential solution, it's likely that some of those users will contribute.

**Comment by th0mk** [comment]
Would be cool to add this! I already have something slightly similar in `.fmcover`, but it would be nice in chart as well.  
Will add this soon.

**Comment by th0mk** [comment]
Small (somewhat related) update: Missing album covers are now also retrieved through Spotify.

You can force this by using `.fmalbum` for an album that has missing album covers. If it finds the album on Spotify, the chart will now have that album cover as well.

**Comment by th0mk** [comment]
After thinking a bit about this, I decided not to do this issue because it could lead to increased amounts of trolling/ people trying to get the bot to post meme images. As an alternative to this, the Spotify album image usage will be improved.
