### ISSUE TITLE
Fmstreak and tagging another user has incorrect text and embed profile picture

### ISSUE THREAD

**Issue by pieman590** [fmbot-discord/fmbot#142]
**Command to reproduce & Last.FM username:**
Command: .fmstreak @userName#0000
Last.FM username: pieman590

**Describe the bug:**
When pinging another user in the .fmstreak command the resulting message with embed shows the pinged user's streak but displays the user who sent the command's discord avatar and display name in the embed.

**Screenshots:**
![image](https://user-images.githubusercontent.com/60752069/126694824-c07fc914-71e0-4760-830a-6a778d2b0d65.png)
As seen in the screenshot the profile of pieman597 is shown but the stats were from truey andystasio.

**Version (use`.fmstatus`):**
![image](https://user-images.githubusercontent.com/60752069/126695179-7c883468-5ee3-4c73-b9b6-7f007060bc5f.png)

**Comment by th0mk** [comment]
Thanks for the report, this has been fixed
