### ISSUE TITLE
.togglecommand doesn't work for commands executed with arguments

### ISSUE THREAD

**Issue by tatsumara** [fmbot-discord/fmbot#158]
**Command to reproduce & Last.FM username:**
.togglecommand fm
.fm some text

**Describe the bug:**
.fm (or any disabled command) shouldn't work in this case, but it still does if it's executed with arguments when it doesn't need any.

**Screenshots:**
![image](https://user-images.githubusercontent.com/50183230/139145716-d16602ac-b3d9-4e10-aa1c-9beb4dd54de1.png)

**Comment by th0mk** [comment]
Should be fixed now, lmk

**Comment by tatsumara** [comment]
works fine now, thank you!
