### ISSUE TITLE
Its possible to @everyone with the ;ap command

### ISSUE THREAD

**Issue by sALTaccount** [fmbot-discord/fmbot#162]
**Command to reproduce & Last.FM username:**
;ap @everyone

**Describe the bug:**
Typing ;ap @everyone allows a user with no perms to mention everybody in the server
The person in the screenshot who did it had no permissions in the server that would allow him to @everyone

**Screenshots:**
https://imgur.com/a/tcR0Oap
There is a custom pfp and name given to fmbot in the screenshot

**Version (use`.fmstatus`):**
Unfortunately I couldn't get the version of fmbot because it was muted shortly after because everyone was spamming @everyone using the command

**Comment by th0mk** [comment]
Thanks for the report, has been fixed
