### ISSUE TITLE
.abt for albums with 12 tracks displays 'Page 1/2' despite having one page

### ISSUE THREAD

**Issue by rkeeley** [fmbot-discord/fmbot#192]
**Command to reproduce & Last.FM username:**

Command: `.abt`
Username: `banger_counter`

**Describe the bug:**

Albums with 12 tracks show `Page 1/2 - 12 total tracks` even though all 12 tracks are displayed on the first page and no buttons are included to change pages. 

**Screenshots:**

![image](https://user-images.githubusercontent.com/6667616/187048484-805dd08d-c77c-4622-8389-987430699e10.png)

**Version (use`.fmstatus`):**

`.fmbot develop` (last.fm server)

**Additional context:**

Seems like [this code](https://github.com/fmbot-discord/fmbot/blob/5859f8111ee751e412ce40110223ec7a4168ddd8/src/FMBot.Bot/Builders/AlbumBuilders.cs#L457) in AlbumBuilders.cs needs special handling for when `12 == tracksDisplayed == albumTracks.Count`.

**Comment by th0mk** [comment]
closing as this is fixed
