### ISSUE TITLE
invalid api key error when trying to login 

### ISSUE THREAD

**Issue by koyqi** [fmbot-discord/fmbot#194]
.login and koyai 

when i try to login to the bot with last.fm it says 
“Invalid API key. If you are a third party developer see our authentication how-to to find out more.” and doesn’t allow me to login 

![EB65F8FA-4DDF-4B70-AA18-F7EA2E01B45E](https://user-images.githubusercontent.com/113778560/190858544-cdb8325c-1c17-4a12-aad7-4f686fa8325c.jpeg)

 as far as i can tell no one else has experienced 
this issue

**Comment by th0mk** [comment]
Fairly sure this is a bug in the Last.fm site, might be related to safari. Still experiencing this?
