### ISSUE TITLE
conflicting aliases

### ISSUE THREAD

**Issue by curiositIy** [fmbot-discord/fmbot#203]
**Command to reproduce & Last.FM username:**
`.friend add lfm:oqt`

**Describe the bug:**
Recently the `.addfriends` command got `.friend` as an alias and that conflicts with the `.friend add` alias.

**Screenshots:**
[imgur](https://i.imgur.com/U8b49BD.png)

**Version (use`.fmstatus`):**
[there was no version displayed, however here is still the command ran just in case](https://i.imgur.com/m2qeMF5.png)

**Additional context:**
The solution is to either remove `.friend` or `.friend add` from the aliases

**Comment by th0mk** [comment]
I was hoping this would remove the `add` keyword if someone uses it, but that's not how it works. Fixed in https://github.com/fmbot-discord/fmbot/commit/96075266ee2baffecf266e392b27c15bc4968d8c
