### ISSUE TITLE
Allow .t command to display all artists. 

### ISSUE THREAD

**Issue by ryanbosley1** [fmbot-discord/fmbot#217]
**What command would you like to see improved or added?**
The .t command, which is the comparison command with another user of their top 1,000 artists, never gives the full lists of similar artists listened to. 

**What exactly should it do?**
I wish for the .t command to list ALL the most similar artists, rather than just a portion of them. It tells me someone has 33 artists similar, and proceeds to show five of them. 

**Additional context**
![Screenshot 2023-02-20 103729](https://user-images.githubusercontent.com/107139609/220148488-6b4f8acc-5129-49db-b15a-53aada97bfa0.png)

For example, as shown in this screenshot, it only gives ten artists. I want to see all 77 rather than 10. The rest of the individuals involved in this community want this improvement on the command also.

**Comment by th0mk** [comment]
I was planning on improving this command with genres and countries, which has now been released.

Unfortunately that means pagination is already being used to switch between those lists, so showing all artists is not possible.

As an alternative I've added the `xxl` option, which doubles the amount of results in the list

For example: `.taste frikandel_ xxl`
