### ISSUE TITLE
A command that show lists of artists in common between two users

### ISSUE THREAD

**Issue by ismailghedamsi** [fmbot-discord/fmbot#222]
**What command would you like to see improved or added?**
A command that shows a list of artists in common between two users

**What exactly should it do?**
The command shows the artists in common and the percentage of artists in common

**Additional context**
I think it's a better way to show how similar two people's tastes are than the compatibility score of lastfm.

**Comment by th0mk** [comment]
This is what the `taste` command does. You can either use the command or right click a user > apps > compare taste.

**Comment by ismailghedamsi** [comment]
Is it possible to extend the taste feature so it includes all artists instead of only the top 1000 artists?
