### ISSUE TITLE
Bot support

### ISSUE THREAD

**Issue by Y3flamex** [fmbot-discord/fmbot#226]
**What command would you like to see improved or added?**
I run a matrix bridge to discord, and the way it works is that a bot sends messages as someone by changing their name and icon, i was wondering if there's a toggle to add bot support to fm

**What exactly should it do?**
toggle whether it supports bots running .fm, limited to 1 account per bot
ex. .bot toggle on

**Comment by th0mk** [comment]
Closing for now, as it's too broad and I don't plan to implement this for now.

**Comment by Y3flamex** [comment]
sorry i didnt see this in a timely manner

> How would we know what Last.fm user is attached to what account? Don't matrix messages that are posted onto Discord use webhooks behind the scenes? (Sorry, not super familiar with Matrix)

usually, matrix bridges are for one person, doubt that multiple people are on it, but you do it so you'd have to do .fm [user] 
you could allow bots to do .fm
