### ISSUE TITLE
Returns Discord Username Incorrectly When It Contains A Period

### ISSUE THREAD

**Issue by 3038salts** [fmbot-discord/fmbot#232]
**Command to reproduce & Last.FM username:**

Rename discord username to include a `.` (if necessary).
Command: `.whoknows`
Username: N/A
**Describe the bug:**

Fmbot inserts a `\` before every occurrence of a `.` only when using the `.whoknows` command.

**Screenshots:**

<img width="516" alt="issue" src="https://github.com/fmbot-discord/fmbot/assets/105826017/117ceed7-9825-43b4-826d-d6d1a7b3b84a">

**Version (use`.fmstatus`):**

`.fmbot`

**Additional context:**
N/A.

**Comment by curiositIy** [comment]
this is an issue with discord currently. fmbot puts backslashes in front of certain characters to prevent markdown but recently discord has been messing with markdown and this happens sometimes now

**Comment by th0mk** [comment]
Discord is also (slowly) rolling out some other changes to how the markdown works. If this still happens after that is done I'll see if I can find a workaround for it
