### ISSUE TITLE
Noah Cyrus incorrectly identified as Miley Cyrus

### ISSUE THREAD

**Issue by MetalMantis** [fmbot-discord/fmbot#233]
**Command to reproduce & Last.FM username:**
.w noah cyrus
username: Metal_Mantis

**Describe the bug:**
Noah Cyrus is referred to as Miley Cyrus by fmbot despite the distinction being recognized by last fm.
Songs by Noah Cyrus are also displayed as being written by Miley Cyrus. 
This issue is not present with Billy Ray Cyrus interestingly, so I'm assuming its some kind of fuzzy search problem
that being said, the issue does not occur with Snoop Dogg and Nate Dogg
**Screenshots:**
![image](https://github.com/fmbot-discord/fmbot/assets/28303596/2a65e0e9-b37f-43e5-9ef3-177c0940f269)
![image](https://github.com/fmbot-discord/fmbot/assets/28303596/693ab118-3913-457c-b600-e1bf67f15bfe)

**Version (use`.fmstatus`):**
2.9.0

**Comment by MetalMantis** [comment]
it is bizarre that https://www.last.fm/music/Noah++Cyrus exists... Is this the only instance of this throughout lastfm?

**Comment by th0mk** [comment]
> Noah Cyrus is referred to as Miley Cyrus by fmbot despite the distinction being recognized by last fm.

Nope, Last.fm still redirects Noah Cyrus to Miley Cyrus.
