### ISSUE TITLE
[ENHANCEMENT] Bot output slur filter

### ISSUE THREAD

**Issue by NavaShield** [fmbot-discord/fmbot#235]
**What would you like to see improved or added?**
Previously when using the bot i've done .fm or .wkt and if the track name/album name contains a slur like the n-word or f-slur it still gets sent. I think it should get censored

**What exactly should it do?**
It should replace every letter except the first and last with asterisks. E.g. f****t

**Comment by th0mk** [comment]
I don't think we'll be adding this, for two main reasons.

First is that it is the responsibility of the user who's using the bot that it doesn't post bad content. If someone 'tricks' the bot into displaying bad content, server staff can take action against the user themselves.

Second is that we don't want to modify or filter text like that. Discord themselves doesn't in their Spotify integration, and neither does any music streaming platform.
