### ISSUE TITLE
Member glitch

### ISSUE THREAD

**Issue by saffk** [fmbot-discord/fmbot#282]
When using the WK command for an artist, the bot shows users that are not even in the server. Due to this issue, multiple crowns have been taken by non existent members. I have provided a screenshot below of how a user named Açai took the crown for Lucki, but when you search the user Açai, the member does not exist. This issue appeared all of sudden yesterday, and there are multiple non existent members for multiple artists. I would appreciate a reasoning for this, thank you!
![IMG_6365](https://github.com/fmbot-discord/fmbot/assets/170830542/59ccadad-a0b5-4964-b48e-f2d2b104dcba)
![IMG_6366](https://github.com/fmbot-discord/fmbot/assets/170830542/d124b217-c06a-420f-a1ab-8d0c5f6a10c5)

**Comment by alluding** [comment]
Refresh your member cache. It's possible these users were in your server but have left, so they claimed the crown and dipped, and the cache just hasn't refreshed.

**Comment by Zeroxysm** [comment]
Run .index or /refreshmembers and check the results again.
