### ISSUE TITLE
Logic for pixel jumble guesses is horrendous

### ISSUE THREAD

**Issue by NiceAesth** [fmbot-discord/fmbot#286]
The current logic for guesses is insanely clunky and incredibly frustrating. Why isn't it just doing a fuzzy string match instead of literally matching for the exact string?

**Screenshots:**
![](https://up.aesth.dev/OFvJV5q6.png)
![](https://up.aesth.dev/hNHyT3mT.png)

**Version (use`.fmstatus`):**
![](https://up.aesth.dev/bc8e0riw.png)

**Comment by th0mk** [comment]
I agree, there is already some string normalization but it isn't good enough. 

Starting from a future update, the following changes will be applied:
- Anything in parentheses will now be removed from the answer, rather then just edition/version/remastered/etc
- If the answer is over 4 characters in length, one mistake in spelling will be allowed
- If the answer is over 10 characters in length, two mistakes in spelling will be allowed

**Comment by th0mk** [comment]
This has now been rolled out! Let me know if you have any more feedback.

**Comment by NiceAesth** [comment]
![](https://up.aesth.dev/COIkrOqk.png) 
this was also something that uhh idk what i was supposed to do to get it lol
