### ISSUE TITLE
You can add lastfmusers to your friends list that don't exist

### ISSUE THREAD

**Issue by th0mk** [fmbot-discord/fmbot#41]
.fmaddfriends needs to:
- Check if the user exists on LastFM
- Check if the user isn't already on your friendslist
- Optional: Check if current friends already exist

Also I'm removing .fmsetfriends, since its confusing and can be replaced by fmaddfriends

**Comment by th0mk** [comment]
Need to add some kind of check to .fmfriends that removes usernames that don't exist

**Comment by g--o** [comment]
Adding: check: adding yourself
(This breaks it too obviously)

**Comment by g--o** [comment]
Adding: duplicate friends
check if friend already exists before adding
