### ISSUE TITLE
Unable to do anything with my profile

### ISSUE THREAD

**Issue by invalidCards** [fmbot-discord/fmbot#59]
**Command to reproduce & Last.FM username:**
.fmrecent, PsiCodes

**Describe the bug:**
Whenever I attempt to try and get my recent scrobbles, the bot poops out even though I have plenty of scrobbles on Last.FM, even recently. .fmset also seems to not be able to set my username, even though it worked the first time.

**Screenshots:**
![img](http://hex.warlo.cc/71d79b60-1e9b-4e14-bdfd-dd32bb4e3aad.png)
![img](http://hex.warlo.cc/95b427df-5750-48d4-975b-352fa92303e0.png)

**Version (use`.fmstatus`):**
0.0.0.0, apparently.

**Additional context:**
I have no idea what's going on at this point.

**Comment by invalidCards** [comment]
Full statistics:
![img](http://hex.warlo.cc/6fd0e051-06de-4c5f-b67c-2f7aa2bc4b40.png)

**Comment by th0mk** [comment]
I can reproduce this issue. Will be looking into it.
The version number bug has been fixed but has not been deployed yet.
![image](https://user-images.githubusercontent.com/9088316/65224548-aef0b800-dac3-11e9-8782-fd847edf058f.png)

**Comment by th0mk** [comment]
After some more investigation this is Last.FM API wide because of issues with the API. There's unfortunately nothing we can do except wait for Last.FM to fix their issues.
