### ISSUE TITLE
Add option to disable commands on a channel basis

### ISSUE THREAD

**Issue by jamster02** [fmbot-discord/fmbot#99]
**What command would you like to see improved or added?**
I want to disable a certain command in a certain channel. Not all commands in a channel, just the chosen ones.

**What exactly should it do?**
I would suggest an optional parameter to .fmtogglecommand that is a channel mention(s) and it would disable the command in that channel.

**Additional context**
Not sure how difficult this would be.

**Comment by th0mk** [comment]
@jamster02 Is this something you no longer need? This would still not be that hard to implement and a useful addition to .fmbot

**Comment by jamster02** [comment]
OK, I thought nobody wanted it so I removed it.

**Comment by AsafSivan1** [comment]
You can disable the channels by go to each channel settings -> permissions -> add the bot in "roles/members" -> disable the option "Read Messages" or "Send Messages".

**Comment by jamster02** [comment]
I meant disable specific commands in certain channels.

**Comment by jamster02** [comment]
Not all commands

**Comment by th0mk** [comment]
@jamster02  Just updated the bot, it's now possible to enable/disable commands in specific channels using `.fmtogglecommand`. 

More info here: https://fmbot.xyz/guildsettings/#fmtogglecommand
